import type { Metadata } from 'next'
import { JetBrains_Mono, Montserrat } from 'next/font/google' // Use Inter em vez de Geist
import './globals.css'

const montSerrant = Montserrat({
  adjustFontFallback: true,
  preload: true,
  variable: '--font-family-notion',
  display: 'swap',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Pesos comuns usados no Notion
})

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Wodbo global',
  description: 'Generated by Peixola',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${montSerrant.variable} ${jetBrainsMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
